# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://fox-point.co.uk
title: Fox Point Roofing and Building services
email: info@fox-point.co.uk
author: Craig Hungate
description:
  As specialists in the trade, we offer the very best roofing services, from repairs to replacement. 
  We have extensive industry knowledge and years of experience, and we are confident we can provide a solution whatever your building or roofing concerns. 
  From bespoke services for more complex cases to simple fixes, we want to help all members of our community and bring our fantastic customer service and friendly reassurance to you. 
copyright: 'Copyright &copy; 2020 Fox Point Roofing and Building services. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty